### ISSUE TITLE
Quick Start Documentation directing to SharePoint template

### ISSUE THREAD

**Issue by rblaine95** [aws-quickstart/quickstart-microsoft-rdgateway#38]
Hi there

I noticed that the [AWS Quick Start Documentation](https://aws-quickstart.github.io/quickstart-microsoft-rdgateway/) under the "[_Launch the Quick Start_](https://github.com/aws-quickstart/quickstart-microsoft-rdgateway/blob/main/docs/partner_editable/deploy_steps.adoc#launch-the-quick-start)" table is pointing to the SharePoint templates in `s3://aws-quickstart/quickstart-microsoft-sharepoint` instead of the RDGateway templates in `s3://aws-quickstart/quickstart-microsoft-rdgateway`

**Comment by ranzanici** [comment]
issue is still there

**Comment by davmayd** [comment]
@rblaine95 @ranzanici this was resolved by the following commit: https://github.com/aws-quickstart/quickstart-microsoft-rdgateway/commit/a59c0bf288cdd1b7dfb34e2b77d63993c8b40e46
