### ISSUE TITLE
Add group for domain\admin to RDGW CAP, NAP, and RAP

### ISSUE THREAD

**Issue by isi-lawson-aws** [aws-quickstart/quickstart-microsoft-rdgateway#6]
When deploying the QS there is an domain\admin user created but the group for that domain\admin user is not added to the network authentication policy, resource authentication policy or connection authentication policy.  The domain\admin user can RDP to the RDGW instances but cannot use the instances as a gateway server without manually adding the user (domain\admin) or group ( domain\users) to the various policies.

**Comment by davmayd** [comment]
This is a stale issue. See https://github.com/aws-quickstart/quickstart-microsoft-rdgateway/blob/main/scripts/Initialize-RDGW.ps1#L65-L79.
