### ISSUE TITLE
Stack fails while trying to create auto scaling group

### ISSUE THREAD

**Issue by vannovv** [aws-quickstart/quickstart-microsoft-rdgateway#7]
I am trying to deploy this into my account and it keeps failing when it tries to create the auto scaling group for the gateways.  I have verified that there are no current issues being reported.  I have verified in Trusted Advisor that I am not at my limit on anything. I have also tried deploying in a different region where we do not have anything else deployed and I am getting the same result.  I do not think it is a problem with autoscaling itself as I was able to deploy 3 Elastic Beanstalks with auto scaling fine. Here are the failed events:

08:56:00 UTC-0600 | CREATE_FAILED | AWS::CloudFormation::Stack | nonprod-management-stack-RDGWStack-9W3CI7VMRIHQ | The following resource(s) failed to create: [RDGWAutoScalingGroup].

  | 08:55:51 UTC-0600 | CREATE_FAILED | AWS::AutoScaling::AutoScalingGroup | RDGWAutoScalingGroup | Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

  | 08:55:50 UTC-0600 | UPDATE_IN_PROGRESS | AWS::AutoScaling::AutoScalingGroup | RDGWAutoScalingGroup | Failed to receive 1 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE

Any help would be appreciated

**Comment by vannovv** [comment]
I went ahead and tried this in a fresh account where we will eventually be deploy our production environment  and it fails there with the same error.

**Comment by vannovv** [comment]
Okay I did not change anything and now its working.  Was taking the defaults the whole time.  Not sure why but glad its going now.

**Comment by yoneal** [comment]
Hi @coder-r were you able to get this working?
I am having the same issue..

**Comment by coder-r** [comment]
Yes. Start of with a blank VPC.

**Comment by yoneal** [comment]
Thanks @coder-r !
Mine worked by enabling auto-assignment of public ip address on launch.
