### ISSUE TITLE
Reproducible error adding Admin user

### ISSUE THREAD

**Issue by WorkinItOut** [aws-quickstart/quickstart-microsoft-rdgateway#8]
I've seen this error a few times on different AWS quick starts so while this pertains to the rdgateway quick start it also impacts others.   

Issue: When specifying the password for the Admin account during the setup, certain special symbols will be interpreted as commands rather than as password characters.

Ex1:
Command invoked: Command b-create-admin (net user /add Admin abc123<123ABC /y)
failure: Command b-create-admin output: The filename, directory name, or volume label syntax is incorrect.

Ex2:
Command invoked: Command b-create-admin (net user /add Admin abc123&123ABC /y)
failure: '123ABC' is not recognized as an internal or external command, operable program or batch file.

Thanks,
K

**Comment by davmayd** [comment]
This is a stale issue. cfn-init has been replaced by an SSM document and therefore the "b-create-admin" command is no longer in use.
